language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CC=gcc-4.8
    - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libcurl4-openssl-dev
    - libssl-dev
    - libjansson-dev
    - libgmp-dev

before_script:
  - autoreconf -f -i -v

script:
  - CFLAGS="-O3 -maes -mssse3 -mtune=generic -DUSE_ASM" CXXFLAGS="$CFLAGS -std=gnu++11" ./configure --with-crypto --with-curl || cat config.log
  - make
